development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rvtweopxfaoyks:_6FOWh65yYf54wsnQg0PEXdq1h@ec2-54-243-54-56.compute-1.amazonaws.com:5432/d76jnn9moptnsc
